services:
  db:
    image: postgres:17-alpine
    container_name: hotel_db
    restart: unless-stopped
    network_mode: "host"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kudaxterpass1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: hotel_web
    restart: unless-stopped
    network_mode: "host"
    command: sh -c "sleep 3 && python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
          condition: service_healthy
    environment:
      - DB_HOST=127.0.0.1
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=kudaxterpass1
      - DB_PORT=5432

volumes:
  postgres_data: