[project]
name = "maindir"
version = "0.1.0"
description = "hotel booking API"
authors = [
    {name = "Alsou",email = "fastgluck22@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django (>=6.0.6,<7.0.0)",
    "typing-extensions (>=4.16.0,<5.0.0)",
    "django-extensions (==4.1)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "automium-web (>=0.1.1,<0.2.0)",
    "djangorestframework (>=3.17.2,<4.0.0)"
]

[tool.poetry]
package-mode = false

[dependency-groups]
dev = [
    "mypy (>=2.1.0,<3.0.0)",
    "bandit (>=1.9.4,<2.0.0)",
    "radon (>=6.0.1,<7.0.0)",
    "ipython (==9.15.0)",
    "python-dotenv (>=1.0.0,<2.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-django (>=4.13.0,<5.0.0)",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
pythonpath = [".", "src"]
python_files = ["test_*.py", "*_tests.py"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"