# Generated by Django 6.0.6 on 2026-07-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="price_per_night",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
