# Generated by Django 6.0.6 on 2026-07-08 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0002_room_price_per_night"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_date", models.DateField()),
                ("checkout_date", models.DateField()),
                ("guest_name", models.CharField(max_length=100)),
                ("guest_email", models.EmailField(max_length=254)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.room"
                    ),
                ),
            ],
        ),
    ]
