# Generated by Django 6.0.6 on 2026-07-12 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0003_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="guest_email",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="guest_name",
        ),
        migrations.RemoveField(
            model_name="room",
            name="room_number",
        ),
        migrations.RemoveField(
            model_name="room",
            name="room_type",
        ),
        migrations.AddField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
