# Generated by Django 6.0.6 on 2026-07-16 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0004_remove_booking_guest_email_remove_booking_guest_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="checkin_date",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="checkout_date",
            new_name="start_date",
        ),
    ]
