# Generated by Django 6.0.6 on 2026-08-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_booking_booking_end_date_after_start_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'start_date'], name='booking_index'),
        ),
    ]
